#encoding: utf-8

categories = [
  f'Category:{s}' for s in (
    'Acrochordidae',
    'Alethinophidia',
    'Aniliidae',
    'Anomalepidae',
    'Anomochilidae',
    'Boidae',
    'Bolyeriidae',
    'Colubrids',
    'Colubrid_stubs',
    'Crotalinae',
    'Crotalis',
    'Cylindrophiidae',
    'Elapidae',
    'Gerrhopilidae',
    'Homalopsidae',
    'Lamprophiidae',
    'Leptotyphlopidae',
    'Loxocemidae',
    'Mambas',
    'Pareidae',
    'Pythonidae',
    'Snakes',
    'Snake_families',
    'Snake_genera',
    'Snake_stubs',
    'Thamnophis',
    'Tropidophiidae',
    'Typhlopidae',
    'Uropeltidae',
    'Venomous_snakes',
    'Viperidae',
    'Viperinae',
    'Xenodermidae',
    'Xenopeltidae',
    'Xenophidiidae',
    'Xenotyphlopidae',
  )
]
